services:
    pgreca.pgsocial.forum:
        class: pgreca\pgsocial\controller\forum
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@request'
            - '@pgreca.pgsocial.helper'
            - '@pgreca.pgsocial.notifyhelper'
            - '@pgreca.pgsocial.social.post_status'
            - '@pgreca.pgsocial.social.social_zebra'
            - '@pgreca.pgsocial.social.social_chat'
            - '@pgreca.pgsocial.social.social_photo'
            - '@pgreca.pgsocial.social.social_tag'
            - '@pgreca.pgsocial.social.social_page'
            - '@template'
            - '@user'
            - '@group_helper'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'   
            - '%core.table_prefix%'            
    pgreca.pgsocial.controller:
        class: pgreca\pgsocial\controller\main
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@request'
            - '@pgreca.pgsocial.helper'
            - '@pgreca.pgsocial.notifyhelper'
            - '@pgreca.pgsocial.social.post_status'
            - '@pgreca.pgsocial.social.social_zebra'
            - '@pgreca.pgsocial.social.social_chat'
            - '@pgreca.pgsocial.social.social_photo'
            - '@pgreca.pgsocial.social.social_tag'
            - '@pgreca.pgsocial.social.social_page'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'   
            - '%core.table_prefix%' 
    pgreca.pgsocial.pages:
        class: pgreca\pgsocial\controller\pages
        arguments:
            - '@files.factory'
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@request'
            - '@pgreca.pgsocial.helper'
            - '@pgreca.pgsocial.notifyhelper'
            - '@pgreca.pgsocial.social.post_status'
            - '@pgreca.pgsocial.social.social_zebra'
            - '@pgreca.pgsocial.social.social_photo'
            - '@pgreca.pgsocial.social.social_tag'
            - '@pgreca.pgsocial.social.social_page'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'   
            - '%core.table_prefix%'    
    pgreca.pgsocial.helper:
        class: pgreca\pgsocial\controller\helper
        arguments:
            - '@auth'
            - '@user'		
            - '@controller.helper'
            - '@pgreca.pgsocial.notifyhelper'
            - '@config'
            - '@dbal.conn'
            - '@log'
            - '@service_container'
            - '@dispatcher'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
    pgreca.pgsocial.notifyhelper:
        class: pgreca\pgsocial\controller\notifyhelper
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@template'
            - '@user'
            - '@service_container'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
    pgreca.pgsocial.notification.type.social_status:
        class: pgreca\pgsocial\notification\social_status
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@pgreca.pgsocial.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }       
    pgreca.pgsocial.notification.type.social_comments:
        class: pgreca\pgsocial\notification\social_comments
        scope: prototype # scope MUST be prototype for this to work!
        arguments:           
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@pgreca.pgsocial.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }
    pgreca.pgsocial.notification.type.social_likes:
        class: pgreca\pgsocial\notification\social_likes
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@pgreca.pgsocial.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }
    pgreca.pgsocial.notification.type.social_tag:
        class: pgreca\pgsocial\notification\social_tag
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@pgreca.pgsocial.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }   
    pgreca.pgsocial.notification.type.social_zebra:
        class: pgreca\pgsocial\notification\social_zebra
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@pgreca.pgsocial.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }   
    pgreca.pgsocial.social.post_status:
        class: pgreca\pgsocial\social\post_status
        arguments:
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@pgreca.pgsocial.helper'       
            - '@pgreca.pgsocial.notifyhelper'     
            - '@pgreca.pgsocial.social.social_photo'
            - '@pgreca.pgsocial.social.social_tag'
            - '@pgreca.pgsocial.social.social_zebra'
            - '@pgreca.pgsocial.social.social_page'
            - '@config'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'                    
    pgreca.pgsocial.social.social_zebra:
        class: pgreca\pgsocial\social\social_zebra
        arguments:
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@pgreca.pgsocial.helper'
            - '@pgreca.pgsocial.notifyhelper'
            - '@config'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'            
    pgreca.pgsocial.social.social_photo:
        class: pgreca\pgsocial\social\social_photo
        arguments:
            - '@template'
            - '@user'		
            - '@controller.helper'
            - '@pgreca.pgsocial.helper'
            - '@pgreca.pgsocial.social.social_tag'
            - '@config'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'  
    pgreca.pgsocial.social.social_tag:
        class: pgreca\pgsocial\social\social_tag
        arguments:
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@pgreca.pgsocial.helper' 
            - '@pgreca.pgsocial.social.social_zebra'
            - '@pgreca.pgsocial.notifyhelper'  
            - '@config'
            - '@dbal.conn'
            - '%core.table_prefix%'       
    pgreca.pgsocial.social.social_chat:
        class: pgreca\pgsocial\social\social_chat
        arguments:
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@config'
            - '@dbal.conn'
            - '@pgreca.pgsocial.helper'
            - '@pgreca.pgsocial.social.social_zebra'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
    pgreca.pgsocial.social.social_page:
        class: pgreca\pgsocial\social\social_page
        arguments:
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@pgreca.pgsocial.helper'       
            - '@pgreca.pgsocial.notifyhelper'     
            - '@pgreca.pgsocial.social.social_photo'
            - '@pgreca.pgsocial.social.social_tag'
            - '@pgreca.pgsocial.social.social_zebra'
            - '@config'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'  
    pgreca.pgsocial.event.listener:
        class: pgreca\pgsocial\event\listener
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@auth'
            - '@request'
            - '@controller.helper'
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@pgreca.pgsocial.helper'
            - '@pgreca.pgsocial.social.post_status'
            - '@pgreca.pgsocial.social.social_photo'
            - '@pgreca.pgsocial.social.social_zebra'
            - '@pgreca.pgsocial.social.social_page'
            - '%core.table_prefix%'
            - '@service_container'
        tags:
            - { name: event.listener }